server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Luisfe26/config-data-microService
  application:
    name: config-service